"""
Phase 8 — Aggregator Agent Node
"""

import logging

from agents.orchestrator import AgentState
from agents.schemas import AggregatorOutput
from agents.structured_call import call_agent_structured, StructuredCallError
from router import ModelRouter

logger = logging.getLogger(__name__)
router = ModelRouter()

SYSTEM_PROMPT = (
    "You are a professional technical writer and research synthesizer. "
    "Your job is to combine all agent outputs into a polished, publication-quality report.\n\n"
    "Formatting requirements:\n"
    "- Use proper markdown with ## headers for each major section\n"
    "- Start with an Executive Summary (3-5 sentences covering the key insight)\n"
    "- Use ### subheaders to organize technical details\n"
    "- Use bullet points for lists of features, trade-offs, or comparisons\n"
    "- Use **bold** for key terms and important figures\n"
    "- End with a ## References section listing all source URLs as a numbered list\n"
    "- End with a ## Conclusion section with a clear, opinionated recommendation\n\n"
    "Code handling — CRITICAL:\n"
    "- If code is provided, you MUST include a ## Code Implementation section\n"
    "- Paste the code EXACTLY and VERBATIM inside a markdown fenced block: ```python ... ```\n"
    "- Do NOT paraphrase, summarise, or omit any part of the provided code\n"
    "- Explain what the code does BEFORE the code block, then show the code block\n\n"
    "CRITICAL: Only include facts, names, dates, and claims that appear "
    "in the provided research findings. Do NOT add historical facts, "
    "names, or details from your own training data that were not in the "
    "research_notes — even if you know them to be true. If research is "
    "incomplete, note the gap explicitly rather than filling it in.\n\n"
    "CRITICAL COMPARISONS: If the prompt asks for a quantitative comparison (like price-to-performance) "
    "but no quantitative data was gathered by upstream agents, you MUST explicitly hedge your conclusion "
    "(e.g., 'could not be quantitatively compared; based on qualitative factors...'). Do NOT assert an unsupported claim.\n\n"
    "Quality bar: the output should read like a well-researched technical blog post "
    "or documentation page, not a chatbot response.\n\n"
    "Return ONLY a raw JSON object (no markdown, no code fences) in this exact shape:\n"
    '{"final_answer": "your complete markdown report here"}\n\n'
    "Rules:\n"
    "- final_answer must contain the full markdown report.\n"
    "- Do NOT include any text outside the JSON object.\n"
    "- Do NOT wrap the JSON in code fences."
)


def aggregator_node(state: AgentState) -> dict:
    research_notes = state.get("research_notes", [])
    research_output = state.get("research_output", {})
    code = state.get("code", "")
    analysis = state.get("analysis", "")

    # Build a deduplicated sources list from notes that look like URLs
    sources_section = ""
    urls = []
    if research_output and "sources" in research_output:
        for s in research_output["sources"]:
            if s["url"] not in urls:
                urls.append(s["url"])
    if not any([research_notes, code.strip(), analysis.strip(), state.get("sql_output")]):
        return {
            "final_output": (
                "⚠️ **Execution Failed**\n\n"
                "No output was generated by any upstream agent. The pipeline failed to produce results.\n\n"
                f"**Latest Error:**\n{state.get('error', 'Unknown Error')}"
            )
        }
                
    if urls:
        sources_section = "## Sources\n" + "\n".join([f"- {url}" for url in urls])

    code_verified = state.get("code_verified", False)
    if code and code.strip():
        if not code_verified:
            # Bug C Fix: Surface failures honestly
            return {
                "final_output": (
                    f"⚠️ **Code Generation Failed**\n\n"
                    f"The agents were unable to produce working code after multiple attempts. "
                    f"The final failing code was:\n```python\n{code}\n```\n\n"
                    f"**Latest Error:**\n{state.get('error', 'Unknown Error')}"
                )
            }

    user_content = f"Research findings:\n{chr(10).join(research_notes)}\n"

    if state.get("sql_output"):
        user_content += f"\n## SQL Database Execution Results\nThe following data was successfully retrieved from the database:\n{state['sql_output']}\n"

    if code and code.strip():
        user_content += (
            "\n## Code to include verbatim\n"
            "The following code was generated by the Coder agent. "
            "You MUST reproduce it EXACTLY inside a ```python ... ``` fenced block "
            "under a ## Code Implementation section — do not paraphrase or omit it.\n"
            f"```python\n{code}\n```\n"
        )

    if analysis and analysis.strip():
        user_content += f"\nAnalysis:\n{analysis}\n"

    if sources_section:
        user_content += f"\n{sources_section}"

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]

    try:
        output: AggregatorOutput = call_agent_structured(
            router=router,
            agent_name="aggregator",
            messages=messages,
            schema=AggregatorOutput,
            max_repairs=3,
        )
        return {"final_output": output.final_answer}
    except Exception as e:
        logger.error("Aggregator failed: %s", e)

        # Fail-visible, not fail-silent: raw fallback content must never
        # look indistinguishable from a real aggregated answer. A user
        # expecting a formatted markdown summary should immediately see
        # that aggregation failed and that what follows is unreviewed
        # raw material, not a polished response.
        fallback_parts = ["⚠️ Aggregation failed — showing raw upstream outputs (unformatted):"]
        
        if research_notes:
            fallback_parts.append("### Raw Research Notes\n" + "\n".join(f"- {n}" for n in research_notes))
        if code:
            fallback_parts.append(f"### Raw Generated Code\n```python\n{code}\n```")
        if analysis:
            fallback_parts.append(f"### Raw Analysis\n{analysis}")

        if len(fallback_parts) == 1:
            fallback = "⚠️ Aggregation failed and no partial output was available from upstream agents."
        else:
            fallback = "\n\n".join(fallback_parts)

        return {"final_output": fallback}